FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04
MAINTAINER Myriota

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV TZ 'Australia/Adelaide'
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y install \
  git \
  curl \
  xxd \
  meson \
  ninja-build \
  gcc \
  python3 \
  python3-pip \
  python-is-python3

RUN echo $TZ > /etc/timezone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

RUN mkdir -p /opt/gcc-arm-13_2_1 && \
    curl -L -o /opt/gcc-arm-13_2_1/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz https://downloads.myriota.com/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz && \
    tar -xvf /opt/gcc-arm-13_2_1/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz -C /opt/gcc-arm-13_2_1 --strip-components=1 && \
    rm /opt/gcc-arm-13_2_1/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
ENV PATH="${PATH}:/opt/gcc-arm-13_2_1/bin"

COPY requirements.txt .
RUN pip3 install -r requirements.txt
ENV PATH="${PATH}:${PWD}/scripts"
